apiVersion: v2
name: signup-ui
description: A Helm chart for DGTDept SIGNUP UI module
type: application
version: 1.2.0-develop
appVersion: ""
dependencies:
  - name: common
    repository: https://charts.bitnami.com/bitnami
    tags:
      - bitnami-common
    version: 1.x.x
home: https://mosip.io
keywords:
  - mosip
  - DGTDept
  - signup-ui
maintainers:
  - email: info@mosip.io
    name: MOSIP
