
dbUserPasswords:
  dbuserPassword: ""
databases:
  mosip_audit:
    enabled: true
    host: "postgres-postgresql.postgres"
    port: 5432
    su:
      user: postgres
      secret:
        name: postgres-postgresql
        key: postgres-password
    dml: 0
    repoUrl: https://github.com/mosip/audit-manager.git
    branch: develop
  mosip_kernel:
    enabled: true
    host: "postgres-postgresql.postgres"
    port: 5432
    su:
      user: postgres
      secret:
        name: postgres-postgresql
        key: postgres-password
    dml: 0
    repoUrl: https://github.com/mosip/commons.git
    branch: develop
  mosip_otp:
    enabled: true
    host: "postgres-postgresql.postgres"
    port: 5432
    su:
      user: postgres
      secret:
        name: postgres-postgresql
        key: postgres-password
    dml: 0
    repoUrl: https://github.com/mosip/otp-manager.git
    branch: develop
  mosip_master:
    enabled: false

  mosip_keymgr:
    enabled: false

  mosip_idmap:
    enabled: false

  mosip_prereg:
    enabled: false

  mosip_idrepo:
    enabled: false

  mosip_ida:
    enabled: false

  mosip_credential:
    enabled: false

  mosip_regprc:
    enabled: false
